[profile.default]
src = 'contracts'
test = 'test'
out = 'out'
libs = ['lib']
solc_version = '0.8.24'
evma = 'cancun'
via_ir = true
fs_permissions = [
  { access = 'read', path = './' },
  { access = 'read-write', path = './metrics' }
]
ffi = true

[profile.ci]
verbosity = 3

[profile.default.invariant]
runs = 2000
depth = 64
fail_on_revert = false

[profile.ci.invariant]
runs = 2000
depth = 64
fail_on_revert = false

[profile.long.invariant]
runs = 20000
depth = 64
fail_on_revert = false

[fuzz]
max_tests = 256
runs = 256
